version: "3"

services:
  gateway:
    container_name: gateway
    image: pienta/gateway:1.0.0
    build: .
    ports:
      - "5000:5000"
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge