version: "3"

services:
  spark-master:
    image: pienta/spark-master:2.4.7
    container_name: spark-master
    build:
      context: docker/spark-master
      dockerfile: docker/spark-master/Dockerfile
    hostname: spark-master
    ports:
      - "8080:8080"
      - "6066:6066"
      - "7077:7077"
    networks:
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
      - ./mnt/spark-apps:/opt/spark-apps
      - ./mnt/spark-data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker-1:
    image: pienta/spark-worker:2.4.7
    container_name: spark-worker-1
    build:
      context: docker/spark-worker
      dockerfile: docker/spark-worker/Dockerfile
    hostname: 10.5.0.3
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    env_file: env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
    networks:
      spark-network:
        ipv4_address: 10.5.0.3
    volumes:
      - ./mnt/spark-apps:/opt/spark-apps
      - ./mnt/spark-data:/opt/spark-data
  spark-worker-2:
    image: pienta/spark-worker:2.4.7
    container_name: spark-worker-2
    build:
      context: docker/spark-worker
      dockerfile: docker/spark-worker/Dockerfile
    hostname: 10.5.0.4
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    env_file: env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
    networks:
      spark-network:
        ipv4_address: 10.5.0.4
    volumes:
      - ./mnt/spark-apps:/opt/spark-apps
      - ./mnt/spark-data:/opt/spark-data
  spark-worker-3:
    image: pienta/spark-worker:2.4.7
    container_name: spark-worker-3
    build:
      context: docker/spark-worker
      dockerfile: docker/spark-worker/Dockerfile
    hostname: 10.5.0.5
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    env_file: env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-3"
    networks:
      spark-network:
        ipv4_address: 10.5.0.5
    volumes:
      - ./mnt/spark-apps:/opt/spark-apps
      - ./mnt/spark-data:/opt/spark-data
  spark-worker-4:
    image: pienta/spark-worker:2.4.7
    container_name: spark-worker-4
    build:
      context: docker/spark-worker
      dockerfile: docker/spark-worker/Dockerfile
    hostname: 10.5.0.6
    depends_on:
      - spark-master
    ports:
      - "8084:8081"
    env_file: env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-4"
    networks:
      spark-network:
        ipv4_address: 10.5.0.6
    volumes:
      - ./mnt/spark-apps:/opt/spark-apps
      - ./mnt/spark-data:/opt/spark-data
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16