version: "3"

services:
  spark-master:
    image: pienta/spark-master:2.4.7
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "6066:6066"
      - "7077:7077"
    networks:
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
      - ./mnt/spark-apps:/opt/spark-apps
      - ./mnt/spark-data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  gateway:
    container_name: gateway
    image: pienta/gateway:1.0.0
    ports:
      - "5000:5000"
    networks:
      - gateway-network
      - spark-network


networks:
  spark-network:
    external: true
  gateway-network:
    driver: bridge