version: "2"

services:
  spark-worker-2:
    image: pienta/spark-worker:2.4.7
    container_name: spark-worker-2
    #    build:
    #      context: docker/spark-worker
    #      dockerfile: docker/spark-worker/Dockerfile
    hostname: 10.5.0.4
#    depends_on:
#      - spark-master
    ports:
      - "8081:8081"
    env_file: env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
    networks:
      spark-network:
        ipv4_address: 10.5.0.4
    volumes:
      - ./mnt/spark-apps:/opt/spark-apps
      - ./mnt/spark-data:/opt/spark-data

networks:
  spark-network:
    external: true