version: "2"

services:
  spark-master:
    image: pienta/spark-master:2.4.7
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "6066:6066"
      - "7077:7077"
    networks:
      spark-network:
        ipv4_address: 10.5.0.2
      - spark-network-bridge
    volumes:
      - ./mnt/spark-apps:/opt/spark-apps
      - ./mnt/spark-data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"

networks:
  spark-network:
    external: true
  spark-network-bridge:
    driver: bridge