version: "2"

services:
  postgres:
    container_name: postgres
    image: pienta/black-box-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./measurements.csv:/var/lib/postgresql/data/measurements.csv
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432/tcp"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=black-box
    networks:
      sparkconfig_spark-network:
        ipv4_address: 10.5.0.7
#    healthcheck:
#      test: nc -z postgres 5432
#      interval: 10s
#      timeout: 5s
#      retries: 5

networks:
  spark-network:
    external: true
