version: "2"

services:
  postgres:
    container_name: postgres
    image: pienta/black-box-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./tcpds.sql:/docker-entrypoint-initdb.d/tcpds.sql
      - ./measurements.csv:/var/lib/postgresql/data/measurements.csv
      - ./tpc-data/1GB/:/var/lib/postgresql/data/
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      spark-network:
        ipv4_address: 10.5.0.24
    ports:
      - "5432:5432/tcp"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=black-box

networks:
  spark-network:
    external: true
